# Generated by Django 6.0 on 2025-12-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporates', '0001_initial'),
        ('psychologists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COUPLE', 'Couple'), ('CORPORATE', 'Corporate')], max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('user_message', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Explicit consent given for this booking')),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='Timestamp when consent was given', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('acknowledgement_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_corporate', models.ForeignKey(blank=True, help_text='Corporate under whose privacy policy consent was taken', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consented_bookings', to='corporates.corporate')),
                ('corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporates.corporate')),
                ('psychologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychologists.psychologist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.appuser')),
            ],
        ),
    ]
