# Generated by Django 6.0 on 2025-12-21 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Email verification token for this booking', unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether booking email has been verified'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True),
        ),
    ]
