# Generated by Django 6.0 on 2025-12-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='acknowledgement_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
