# Generated by Django 6.0 on 2025-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_acknowledgement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_verification_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time verification email was sent', null=True),
        ),
    ]
