# Generated by Django 6.0 on 2025-12-24 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_last_verification_email_sent_at'),
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='last_verification_email_sent_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='alternate_slots',
            field=models.TextField(blank=True, help_text='Admin suggested alternate slots'),
        ),
        migrations.AddField(
            model_name='booking',
            name='approved_slot_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='approved_slot_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='CONFIRMED', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='online', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_period',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('CUSTOM', 'Custom Range')], default='CUSTOM', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consent_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consented_bookings', to='corporates.corporate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
