# Generated by Django 6.0 on 2025-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_last_verification_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_verification_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time verification email was sent', null=True),
        ),
    ]
