# Generated by Django 6.0 on 2025-12-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_last_verification_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='Preferred date requested by the user', null=True),
        ),
    ]
