# Generated by Django 6.0 on 2025-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_access_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last time user verified email to access this booking', null=True),
        ),
    ]
