# Generated by Django 6.0 on 2025-12-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_last_access_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
