# Generated by Django 6.0 on 2025-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_admin_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
