# Generated by Django 6.0 on 2025-12-24 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_confirmation_token_booking_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
